### ISSUE TITLE
Provide a Replacement for hash "correct Tag" Test

### ISSUE THREAD

**Issue by stenolog** [input-output-hk/scrypto#111]
This test:

https://github.com/input-output-hk/scrypto/blob/1d2db265cfaf3f884f04cb609ad4a5993f748a42/shared/src/test/scala/scorex/crypto/hash/HashTest.scala#L59-L69

is not functional within scala 2.

This came up during work on

- https://github.com/input-output-hk/scrypto/pull/108

### Reproduce

just replace 32/64 `hash.DigestSize shouldBe 32` with a wrong value, the test will not fail.

### Tasks

- [ ] disable the non-functioning part
- [ ] find a solution to have the Tag available in runtime
- [ ] provide a new test (for scala 2 and 3)

**Comment by stenolog** [comment]
Potential fix: [pull-108-2fa4a7e](https://github.com/input-output-hk/scrypto/pull/108/commits/2fa4a7eccd45298257089a62a9b44cf48469dc61)
